<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5rCR5LyX');
$cfg_Cs[2]=array(0,1,1,'5rCR5LyX5pyN5Yqh');
$cfg_Cs[3]=array(0,1,1,'5pyN5Yqh5Zui6Zif');
$cfg_Cs[4]=array(0,1,1,'5aWX6aSQ5pyN5Yqh');
$cfg_Cs[5]=array(0,1,1,'5rCR5LyX5Yqo5oCB');
$cfg_Cs[6]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[7]=array(0,1,1,'5Yy76Zmi546v5aKD');
$cfg_Cs[8]=array(0,1,1,'5pyN5Yqh5Lq6576k');
$cfg_Cs[9]=array(2,1,1,'5Y2K6Ieq55CG6ICB5Lq6');
$cfg_Cs[10]=array(2,1,1,'5aSx6IO95aSx5pm66ICB5Lq6');
$cfg_Cs[11]=array(2,1,1,'6ZW/5pyf5Y2n5bqK6ICB5Lq6');
$cfg_Cs[12]=array(2,1,1,'5Li057uI5YWz5oCA6ICB5Lq6');
$cfg_Cs[13]=array(0,1,1,'5p2l6Zmi6Lev57q/');
?>