<?php
$z[0]=Array("field","",426,446);
$z[0][4]['name']="title";
$z[1]=Array("include","",1266,1311);
$z[1][4]['filename']="include/xl_nav.htm";
$z[2]=Array("field","",1578,1607);
$z[2][4]['name']="position";
$z[3]=Array("field","",1655,1674);
$z[3][4]['name']="title";
$z[4]=Array("field","",1970,1988);
$z[4][4]['name']="body";
$z[5]=Array("arclist","\r\n            <li>[field:title/]<a href=\"[field:arcurl/]\" target=\"_blank\">查看></a></li>\r\n            ",2317,2486);
$z[5][4]['titlelen']="30";
$z[5][4]['infolen']="120";
$z[5][4]['row']="5";

?>