<li>
                	<h1><img src="[field:litpic/]"></h1>
                    <div>
                    	<h2>[field:title /]</h2>
                        <p>[field:description function='cn_substr(html2text(@me),120)'/]... <a href="[field:arcurl /]" target="_blank">【详情】</a></p>
                        <h3>
                        	<a href="#" target="_blank">点击拨打</a>
                            <a href="#" target="_blank">在线咨询</a>
                        </h3>
                    </div>
                </li>