<?php
$z[0]=Array("field","",426,452);
$z[0][4]['name']="title";
$z[1]=Array("include","",988,1033);
$z[1][4]['filename']="include/xl_nav.htm";
$z[2]=Array("field","",1584,1613);
$z[2][4]['name']="position";
$z[3]=Array("list","\r\n            	<li>\r\n                	<h1><img src=\"[field:litpic/]\"></h1>\r\n                    <div>\r\n                    	<h2>[field:title /]</h2>\r\n                        <p>[field:description function='cn_substr(html2text(@me),120)'/]... <a href=\"[field:arcurl /]\" target=\"_blank\">【详情】</a></p>\r\n                        <h3>\r\n                        	<a href=\"#\" target=\"_blank\">点击拨打</a>\r\n                            <a href=\"#\" target=\"_blank\">在线咨询</a>\r\n                        </h3>\r\n                    </div>\r\n                </li>\r\n                \r\n                ",2599,3265);
$z[3][4]['pagesize']="4";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>