<?php
$z[0]=Array("field","",426,446);
$z[0][4]['name']="title";
$z[1]=Array("include","",1266,1311);
$z[1][4]['filename']="include/xl_nav.htm";
$z[2]=Array("field","",1526,1555);
$z[2][4]['name']="position";
$z[3]=Array("field","",1631,1651);
$z[3][4]['name']="title";
$z[4]=Array("list","\r\n    	<div class=\"lb_wz\">\r\n        	<h5>[field:title/]</h5>\r\n        	<p>[field:description/]<a href=\"[field:arcurl /]\" target=\"_blank\">【详情】</a></p>\r\n        </div>\r\n        ",2517,2736);
$z[4][4]['pagesize']="4";
$z[5]=Array("pagelist","",2776,2847);
$z[5][4]['istitem']="index,pre,next,end,option,info,";
$z[5][4]['listsize']="5";

?>